config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :hostnames_ips
  resources :hostnames
  resources :ips

  # API
  scope module: 'api' do
    scope '/api' do
      resources :docs, only: [:index]

      namespace :v1 do
        # resources :ips
        match '/dns', to: 'ips#index', via: :get
        match '/dns', to: 'ips#create', via: :post
      end
    end
  end
end

app/models/hostname.rb
class Hostname < ApplicationRecord

  has_and_belongs_to_many :ips

  validates :hostname, presence: true
  validate :valid_hostname
  validates_uniqueness_of :hostname

  def valid_hostname
    if hostname.present? && hostname.match(/^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix).present? === false
      errors.add(:hostname, 'only valid domains')
    end
  end

end

app/controllers/hostnames_controller.rb
class HostnamesController < ApplicationController
  before_action :set_hostname, only: [:show, :edit, :update, :destroy]

  # GET /hostnames
  # GET /hostnames.json
  def index
    @hostnames = Hostname.all
  end

  # GET /hostnames/1
  # GET /hostnames/1.json
  def show
  end

  # GET /hostnames/new
  def new
    @hostname = Hostname.new
  end

  # GET /hostnames/1/edit
  def edit
  end

  # POST /hostnames
  # POST /hostnames.json
  def create
    @hostname = Hostname.new(hostname_params)

    respond_to do |format|
      if @hostname.save
        format.html { redirect_to @hostname, notice: 'Hostname was successfully created.' }
        format.json { render :show, status: :created, location: @hostname }
      else
        format.html { render :new }
        format.json { render json: @hostname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hostnames/1
  # PATCH/PUT /hostnames/1.json
  def update
    respond_to do |format|
      if @hostname.update(hostname_params)
        format.html { redirect_to @hostname, notice: 'Hostname was successfully updated.' }
        format.json { render :show, status: :ok, location: @hostname }
      else
        format.html { render :edit }
        format.json { render json: @hostname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostnames/1
  # DELETE /hostnames/1.json
  def destroy
    @hostname.destroy
    respond_to do |format|
      format.html { redirect_to hostnames_url, notice: 'Hostname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostname
      @hostname = Hostname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostname_params
      params.require(:hostname).permit(:hostname)
    end
end

app/views/hostnames/_form.html.erb
<%= form_with(model: hostname, local: true) do |form| %>
  <% if hostname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hostname.errors.count, "error") %> prohibited this hostname from being saved:</h2>

      <ul>
        <% hostname.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hostname %>
    <%= form.text_field :hostname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hostnames/edit.html.erb
<h1>Editing Hostname</h1>

<%= render 'form', hostname: @hostname %>

<%= link_to 'Show', @hostname %> |
<%= link_to 'Back', hostnames_path %>

app/views/hostnames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hostnames</h1>

<table>
  <thead>
    <tr>
      <th>Hostname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hostnames.each do |hostname| %>
      <tr>
        <td><%= hostname.hostname %></td>
        <td><%= link_to 'Show', hostname %></td>
        <td><%= link_to 'Edit', edit_hostname_path(hostname) %></td>
        <td><%= link_to 'Destroy', hostname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hostname', new_hostname_path %>

app/views/hostnames/new.html.erb
<h1>New Hostname</h1>

<%= render 'form', hostname: @hostname %>

<%= link_to 'Back', hostnames_path %>

app/views/hostnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hostname:</strong>
  <%= @hostname.hostname %>
</p>

<%= link_to 'Edit', edit_hostname_path(@hostname) %> |
<%= link_to 'Back', hostnames_path %>