config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :hostnames_ips
  resources :hostnames
  resources :ips

  # API
  scope module: 'api' do
    scope '/api' do
      resources :docs, only: [:index]

      namespace :v1 do
        # resources :ips
        match '/dns', to: 'ips#index', via: :get
        match '/dns', to: 'ips#create', via: :post
      end
    end
  end
end

app/models/hostnames_ip.rb
class HostnamesIp < ApplicationRecord

  belongs_to :hostname
  belongs_to :ip

  validates_uniqueness_of :hostname, scope: :ip

end

app/controllers/hostnames_ips_controller.rb
class HostnamesIpsController < ApplicationController
  before_action :set_hostnames_ip, only: [:show, :edit, :update, :destroy]

  # GET /hostnames_ips
  # GET /hostnames_ips.json
  def index
    @hostnames_ips = HostnamesIp.all
  end

  # GET /hostnames_ips/1
  # GET /hostnames_ips/1.json
  def show
  end

  # GET /hostnames_ips/new
  def new
    @hostnames_ip = HostnamesIp.new
  end

  # GET /hostnames_ips/1/edit
  def edit
  end

  # POST /hostnames_ips
  # POST /hostnames_ips.json
  def create
    @hostnames_ip = HostnamesIp.new(hostnames_ip_params)

    respond_to do |format|
      if @hostnames_ip.save
        format.html { redirect_to @hostnames_ip, notice: 'Hostnames ip was successfully created.' }
        format.json { render :show, status: :created, location: @hostnames_ip }
      else
        format.html { render :new }
        format.json { render json: @hostnames_ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hostnames_ips/1
  # PATCH/PUT /hostnames_ips/1.json
  def update
    respond_to do |format|
      if @hostnames_ip.update(hostnames_ip_params)
        format.html { redirect_to @hostnames_ip, notice: 'Hostnames ip was successfully updated.' }
        format.json { render :show, status: :ok, location: @hostnames_ip }
      else
        format.html { render :edit }
        format.json { render json: @hostnames_ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostnames_ips/1
  # DELETE /hostnames_ips/1.json
  def destroy
    @hostnames_ip.destroy
    respond_to do |format|
      format.html { redirect_to hostnames_ips_url, notice: 'Hostnames ip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostnames_ip
      @hostnames_ip = HostnamesIp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostnames_ip_params
      params.require(:hostnames_ip).permit(:hostname_id, :ip_id)
    end
end

app/views/hostnames_ips/_form.html.erb
<%= form_with(model: hostnames_ip, local: true) do |form| %>
  <% if hostnames_ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hostnames_ip.errors.count, "error") %> prohibited this hostnames_ip from being saved:</h2>

      <ul>
        <% hostnames_ip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hostname_id %>
    <%= form.text_field :hostname_id %>
  </div>

  <div class="field">
    <%= form.label :ip_id %>
    <%= form.text_field :ip_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hostnames_ips/edit.html.erb
<h1>Editing Hostnames Ip</h1>

<%= render 'form', hostnames_ip: @hostnames_ip %>

<%= link_to 'Show', @hostnames_ip %> |
<%= link_to 'Back', hostnames_ips_path %>

app/views/hostnames_ips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hostnames Ips</h1>

<table>
  <thead>
    <tr>
      <th>Hostname</th>
      <th>Ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hostnames_ips.each do |hostnames_ip| %>
      <tr>
        <td><%= hostnames_ip.hostname_id %></td>
        <td><%= hostnames_ip.ip_id %></td>
        <td><%= link_to 'Show', hostnames_ip %></td>
        <td><%= link_to 'Edit', edit_hostnames_ip_path(hostnames_ip) %></td>
        <td><%= link_to 'Destroy', hostnames_ip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hostnames Ip', new_hostnames_ip_path %>

app/views/hostnames_ips/new.html.erb
<h1>New Hostnames Ip</h1>

<%= render 'form', hostnames_ip: @hostnames_ip %>

<%= link_to 'Back', hostnames_ips_path %>

app/views/hostnames_ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hostname:</strong>
  <%= @hostnames_ip.hostname_id %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @hostnames_ip.ip_id %>
</p>

<%= link_to 'Edit', edit_hostnames_ip_path(@hostnames_ip) %> |
<%= link_to 'Back', hostnames_ips_path %>