config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :hostnames_ips
  resources :hostnames
  resources :ips

  # API
  scope module: 'api' do
    scope '/api' do
      resources :docs, only: [:index]

      namespace :v1 do
        # resources :ips
        match '/dns', to: 'ips#index', via: :get
        match '/dns', to: 'ips#create', via: :post
      end
    end
  end
end

app/models/ip.rb
class Ip < ApplicationRecord

  has_and_belongs_to_many :hostnames

  validates :ip, presence: true
  validate :valid_ipv4
  validates_uniqueness_of :ip

  def valid_ipv4
    if ip.present? && ip.match(/\b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}\b/).present? === false
      errors.add(:ip, 'only valid IPV4')
    end
  end

end

app/controllers/api/v1/ips_controller.rb
module Api::V1
	class IpsController < ApiController

		# GET api/v1/dns
		def index
      page = params[:page]? params[:page].to_i : 1
      limit = 10

			@ips = Ip.includes(:hostnames).limit(limit).offset((page - 1) * limit)
		end

		# POST api/v1/dns
		def create
			hostnames_ip = JSON.parse(params.to_json)
			ip = hostnames_ip['ip']
			hostnames = hostnames_ip['hostnames']

			@ip = Ip.new(ip: ip)
			if @ip.save
				hostnames.map { |hostname|
          Hostname.new(hostname: hostname['hostname']).save
          hostname = Hostname.find_by(hostname: hostname['hostname'])
          if hostname
            HostnamesIp.new(ip_id: @ip.id, hostname_id: hostname.id).save
          end
        }
      else
				render json: { error: @ip.errors.messages }, status: :not_acceptable
			end
		end

	end
end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  before_action :set_ip, only: [:show, :edit, :update, :destroy]

  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.all
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
  end

  # GET /ips/new
  def new
    @ip = Ip.new
  end

  # GET /ips/1/edit
  def edit
  end

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(ip_params)

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, notice: 'Ip was successfully created.' }
        format.json { render :show, status: :created, location: @ip }
      else
        format.html { render :new }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ips/1
  # PATCH/PUT /ips/1.json
  def update
    respond_to do |format|
      if @ip.update(ip_params)
        format.html { redirect_to @ip, notice: 'Ip was successfully updated.' }
        format.json { render :show, status: :ok, location: @ip }
      else
        format.html { render :edit }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip.destroy
    respond_to do |format|
      format.html { redirect_to ips_url, notice: 'Ip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip
      @ip = Ip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_params
      params.require(:ip).permit(:ip)
    end
end

app/views/ips/_form.html.erb
<%= form_with(model: ip, local: true) do |form| %>
  <% if ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ip.errors.count, "error") %> prohibited this ip from being saved:</h2>

      <ul>
        <% ip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ips/edit.html.erb
<h1>Editing Ip</h1>

<%= render 'form', ip: @ip %>

<%= link_to 'Show', @ip %> |
<%= link_to 'Back', ips_path %>

app/views/ips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ips</h1>

<table>
  <thead>
    <tr>
      <th>Ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ips.each do |ip| %>
      <tr>
        <td><%= ip.ip %></td>
        <td><%= link_to 'Show', ip %></td>
        <td><%= link_to 'Edit', edit_ip_path(ip) %></td>
        <td><%= link_to 'Destroy', ip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ip', new_ip_path %>

app/views/ips/new.html.erb
<h1>New Ip</h1>

<%= render 'form', ip: @ip %>

<%= link_to 'Back', ips_path %>

app/views/ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @ip.ip %>
</p>

<%= link_to 'Edit', edit_ip_path(@ip) %> |
<%= link_to 'Back', ips_path %>